-- 颜色主题与高亮覆盖

local onedark = require("onedarkpro.helpers")
local colors = onedark.get_colors("onedark")

-- onedark 主题专属高亮覆盖 (必须在 colorscheme 之前注册)
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "onedark",
  callback = function()
    vim.api.nvim_set_hl(0, "@lsp.type.namespace", { link = "Type" })
    vim.api.nvim_set_hl(0, "@lsp.type.member", { link = "@function" })
    vim.api.nvim_set_hl(0, "tsxCloseString", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "@parameter", { fg = colors.orange })
    vim.api.nvim_set_hl(0, "typescriptDefaultImportName", { fg = colors.red })
    vim.api.nvim_set_hl(0, "typescriptIdentifierName", { fg = colors.red })
    vim.api.nvim_set_hl(0, "typescriptImportBlock", { fg = colors.red })
    vim.api.nvim_set_hl(0, "typescriptBraces", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "@function.builtin", { fg = colors.cyan })
    vim.api.nvim_set_hl(0, "typescriptEndColons", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "typescriptObjectLabel", { link = "@property" })
    vim.api.nvim_set_hl(0, "typescriptFuncCallArg", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "typescriptArrowFunc", { link = "keyword" })
    vim.api.nvim_set_hl(0, "tsxTagName", { link = "Type" })
    vim.api.nvim_set_hl(0, "typescriptDecorator", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "htmlArg", { fg = colors.orange })
    vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {})
    vim.api.nvim_set_hl(0, "NvimTreeRootFolder", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "NvimTreeFolderName", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "NvimTreeFolderArrowOpen", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "NvimTreeFolderArrowClosed", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "typescriptFuncTypeArrow", { link = "keyword" })
    vim.api.nvim_set_hl(0, "lessClass", { fg = colors.orange })
    vim.api.nvim_set_hl(0, "cssPositioningAttr", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "cssFunctionName", { fg = colors.cyan })
    vim.api.nvim_set_hl(0, "cssCustomProp", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "cssUnitDecorators", { fg = colors.red })
    vim.api.nvim_set_hl(0, "lessFunction", { fg = colors.cyan })
    vim.api.nvim_set_hl(0, "cssBraces", { fg = colors.orange })
    vim.api.nvim_set_hl(0, "typescriptCastKeyword", { link = "keyword" })
    vim.api.nvim_set_hl(0, "typescriptOperator", { link = "keyword" })
    vim.api.nvim_set_hl(0, "tsxAttrib", { fg = colors.orange })
    vim.api.nvim_set_hl(0, "@tag.tsx", { link = "Type" })
    vim.api.nvim_set_hl(0, "@type.tsx", { link = "@variable" })
    vim.api.nvim_set_hl(0, "@tag.builtin.tsx", { link = "@tag" })
    vim.api.nvim_set_hl(0, "@markup.heading", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "@lsp.typemod.variable.readonly.typescriptreact", { fg = colors.yellow })
    vim.api.nvim_set_hl(0, "@lsp.typemod.variable.readonly.typescript", { fg = colors.yellow })
    vim.api.nvim_set_hl(0, "@lsp.typemod.variable.readonly.javascript", { fg = colors.yellow })
    vim.api.nvim_set_hl(0, "@tag.javascript", { link = "Type" })
    vim.api.nvim_set_hl(0, "@type.javascript", { link = "@variable" })
    vim.api.nvim_set_hl(0, "@tag.builtin.javascript", { link = "@tag" })
    vim.api.nvim_set_hl(0, "@lsp.typemod.variable.readonly.javascriptreact", { fg = colors.yellow })
    vim.api.nvim_set_hl(0, "@tag.attribute.javascript", { fg = colors.orange })
    vim.api.nvim_set_hl(0, "@punctuation.bracket.tsx", { link = "@punctuation.bracket" })
    vim.api.nvim_set_hl(0, "@punctuation.bracket.typescript", { link = "@punctuation.bracket" })
    vim.api.nvim_set_hl(0, "@odp.import_module.python", { link = "Type" })
    vim.api.nvim_set_hl(0, "@keyword.operator.lua", { link = "keyword" })
    vim.api.nvim_set_hl(0, "constructor", { link = "keyword" })
    vim.api.nvim_set_hl(0, "@variable.parameter.kotlin", { link = "@constant" })
    vim.api.nvim_set_hl(0, "@punctuation.bracket.kotlin", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "@variable.builtin.kotlin", { link = "keyword" })
    vim.api.nvim_set_hl(0, "@attribute.kotlin", { link = "Type" })
    vim.api.nvim_set_hl(0, "@operator.kotlin", { link = "keyword" })
    vim.api.nvim_set_hl(0, "@function.builtin.kotlin", { link = "keyword" })
  end,
})

vim.cmd("colorscheme onedark")
